### ISSUE TITLE
ReactNavigtion.Types module namespacing

### ISSUE THREAD

**Issue by idkjs** [reason-react-native/react-navigation#5]
Opening `ReactNavigation` exposes the `Types` module which clashes with a projects `Types` module if they have one.. You may want to consider renaming it.

<img width="741" alt="Screenshot 2019-09-18 at 3 13 56 PM" src="https://user-images.githubusercontent.com/2370391/65178540-f83efa00-da26-11e9-8697-63ea09bd67eb.png">

**Comment by cknitt** [comment]
Done already, see #2. 😉
